openapi: "3.1.0"
info:
  title: "VientosDelSur Room API"
  description: "API for managing rooms and room distributions"
  version: "1.0.0"
paths:
  /room:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends RoomDto>"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Nothing"
  /room/distribution:
    get:
      description: ""
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends RoomStateDto>"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No room distribution found"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
                enum:
                  - "REQUEST_TIMEOUT"
                  - "NOT_FOUND"
                  - "TOO_MANY_REQUESTS"
                  - "NO_INTERNET"
                  - "SERVER"
                  - "SERIALIZATION"
                  - "UNKNOWN"
                  - "LOGICAL"
  /room/distribution/generate:
    post:
      description: ""
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_LocalDate"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No data to work with"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
                enum:
                  - "REQUEST_TIMEOUT"
                  - "NOT_FOUND"
                  - "TOO_MANY_REQUESTS"
                  - "NO_INTERNET"
                  - "SERVER"
                  - "SERIALIZATION"
                  - "UNKNOWN"
                  - "LOGICAL"
  /room/distribution/{housekeeperId}:
    get:
      description: ""
      parameters:
        - name: "housekeeperId"
          in: "path"
          required: true
          schema:
            type: "integer"
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
                Example#2:
                  value: "Invalid housekeeper ID"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends RoomStateDto>"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No room distribution found"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
                enum:
                  - "REQUEST_TIMEOUT"
                  - "NOT_FOUND"
                  - "TOO_MANY_REQUESTS"
                  - "NO_INTERNET"
                  - "SERVER"
                  - "SERIALIZATION"
                  - "UNKNOWN"
                  - "LOGICAL"
components:
  schemas:
    RoomDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        roomNumber:
          type: "string"
        roomType:
          type: "string"
      required:
        - "id"
        - "roomNumber"
        - "roomType"
    BaseResponseDto:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - "message"
        - "timestamp"
    BaseResponseDto_List<? extends RoomDto>:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/RoomDto"
    RoomCleaningStatusDto:
      type: "object"
      properties:
        status:
          type: "string"
          enum:
            - "PENDING"
            - "IN_PROGRESS"
            - "IN_REVISION"
            - "DONE"
        updatedAt:
          type: "string"
          format: "date-time"
          nullable: true
      required:
        - "status"
    RoomStateDto:
      type: "object"
      properties:
        room:
          $ref: "#/components/schemas/RoomDto"
        cleaningType:
          type: "string"
        currentStatus:
          $ref: "#/components/schemas/RoomCleaningStatusDto"
      required:
        - "room"
        - "cleaningType"
        - "currentStatus"
    BaseResponseDto_List<? extends RoomStateDto>:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/RoomStateDto"
    Map:
      type: "object"
      properties: { }
    Map_LocalDate:
      type: "string"