openapi: "3.1.0"
info:
  title: "VientosDelSur Shift API"
  description: "API for managing staff shifts"
  version: "1.0.0"
paths:
  /shifts/distribute:
    post:
      summary: "Schedule shifts"
      description: "Generates and returns a shift distribution for staff"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ShiftDistributionResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Something happened: {error message}"

components:
  schemas:
    ShiftDistributionResponse:
      type: "object"
      properties:
        shifts:
          type: "array"
          items:
            $ref: "#/components/schemas/ShiftDto"
      required:
        - "shifts"
    ShiftDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        employeeId:
          type: "integer"
          format: "int32"
        startTime:
          type: "string"
          format: "date-time"
        endTime:
          type: "string"
          format: "date-time"
        shiftType:
          type: "string"
          enum: ["MORNING", "AFTERNOON", "NIGHT"]
      required:
        - "employeeId"
        - "startTime"
        - "endTime"
        - "shiftType"