openapi: "3.1.0"
info:
  title: "VientosDelSur Shift API"
  description: "API for managing staff shifts"
  version: "1.0.0"
paths:
  /shifts/employee/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_ScheduleDto"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No shifts found"
  /shifts/employees-working:
    get:
      description: ""
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends EmployeeDto>"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No employees on shift"
  /shifts/scheduling:
    get:
      description: ""
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends MonthlyShiftDistributionDto>"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /shifts/scheduling/generate:
    post:
      description: ""
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid date format"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_List<? extends MonthlyShiftDistributionDto>"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /shifts/scheduling/publish:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/MonthlyShiftDistributionDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Malformed body"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Saved draft successfully"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    ShiftDto:
      type: "object"
      properties:
        startTime:
          type: "string"
          format: "partial-time"
        endTime:
          type: "string"
          format: "partial-time"
        type:
          type: "string"
          enum:
            - "GENERAL_DUTY"
            - "KITCHEN_ASSISTANT"
            - "KITCHEN_LEAD"
      required:
        - "startTime"
        - "endTime"
        - "type"
    ShiftDateDto:
      type: "object"
      properties:
        shift:
          $ref: "#/components/schemas/ShiftDto"
        date:
          type: "string"
          format: "date"
      required:
        - "shift"
        - "date"
    ScheduleDto:
      type: "object"
      properties:
        workingDays:
          type: "array"
          items:
            $ref: "#/components/schemas/ShiftDateDto"
        daysOff:
          type: "array"
      required:
        - "workingDays"
        - "daysOff"
    BaseResponseDto:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - "message"
        - "timestamp"
    BaseResponseDto_ScheduleDto:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        data:
          $ref: "#/components/schemas/ScheduleDto"
    EmployeeDto:
      type: "object"
      properties: { }
    BaseResponseDto_List<? extends EmployeeDto>:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/EmployeeDto"
    Get:
      type: "object"
      properties: { }
    MonthlyShiftDistributionDto:
      type: "object"
      properties:
        employee:
          $ref: "#/components/schemas/Get"
        scheduleDto:
          $ref: "#/components/schemas/ScheduleDto"
      required:
        - "employee"
        - "scheduleDto"
    BaseResponseDto_List<? extends MonthlyShiftDistributionDto>:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/MonthlyShiftDistributionDto"