openapi: "3.1.0"
info:
  title: "VientosDelSur Shift API"
  description: "API for managing staff shifts"
  version: "1.0.0"
paths:
  /shifts/employees-working:
    get:
      summary: "Get employees working on a specific date"
      description: "Returns a list of employees scheduled to work on the specified date"
      parameters:
        - name: "date"
          in: "query"
          required: true
          description: "The date to check for working employees (format YYYY-MM-DD)"
          schema:
            type: "string"
            format: "date"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/EmployeeDto"
        "400":
          description: "Bad Request"
          content:
            'text/plain':
              schema:
                type: "string"
              examples:
                MissingDate:
                  value: "Date parameter is required"
                InvalidFormat:
                  value: "Invalid date format"
        "404":
          description: "Not Found"
          content:
            'text/plain':
              schema:
                type: "string"
              examples:
                NoEmployees:
                  value: "No employees on shift"
        "500":
          description: "Internal Server Error"
          content:
            'text/plain':
              schema:
                type: "string"
              examples:
                Error:
                  value: "Error retrieving employees: {error message}"
  /shifts/distribute:
    post:
      summary: "Schedule shifts"
      description: "Generates and returns a shift distribution for staff"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ShiftDistributionResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Something happened: {error message}"

components:
  schemas:
    EmployeeDto:
      type: "object"
      description: "Employee information"
      # Note: Define this schema with appropriate properties based on your actual DTO
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        # Add other employee properties as needed
    ShiftDistributionResponse:
      type: "object"
      properties:
        shifts:
          type: "array"
          items:
            $ref: "#/components/schemas/ShiftDto"
      required:
        - "shifts"
    ShiftDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        employeeId:
          type: "integer"
          format: "int32"
        startTime:
          type: "string"
          format: "date-time"
        endTime:
          type: "string"
          format: "date-time"
        shiftType:
          type: "string"
          enum: ["MORNING", "AFTERNOON", "NIGHT"]
      required:
        - "employeeId"
        - "startTime"
        - "endTime"
        - "shiftType"