openapi: 3.0.0
info:
  title: Vientos del Sur Employee API
  version: 1.0.0
  description: API for managing employees
paths:
  /employee:
    get:
      summary: Get all employees
      responses:
        '200':
          description: List of employees retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeGet'
        '404':
          description: No employees found
          content:
            application/json:
              schema:
                type: string
                example: "Nothing"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                example: "Something happened: error details"
    post:
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
      responses:
        '201':
          description: Employee created successfully
        '400':
          description: Invalid employee data
        '500':
          description: Internal server error
  /employee/active/{userId}:
    get:
      summary: Check if employee is active
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to check
          schema:
            type: string
      responses:
        '200':
          description: Employee is active
        '400':
          description: User ID is required
        '404':
          description: Employee not found or not active
components:
  schemas:
    EmployeeGet:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        dayOff:
          type: string
          enum: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        hireDate:
          type: string
          format: date-time
        occupation:
          $ref: '#/components/schemas/EmployeeOccupation'
        housekeeperDto:
          $ref: '#/components/schemas/Housekeeper'
      required:
        - id
        - firstName
        - lastName
        - phoneNumber
        - dayOff
        - hireDate
        - occupation
    EmployeeCreate:
      type: object
      properties:
        userDto:
          $ref: '#/components/schemas/User'
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        dayOff:
          type: string
          enum: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        hireDate:
          type: string
          format: date-time
        occupation:
          $ref: '#/components/schemas/EmployeeOccupation'
        housekeeperDto:
          $ref: '#/components/schemas/Housekeeper'
      required:
        - userDto
        - firstName
        - lastName
        - phoneNumber
        - dayOff
        - hireDate
        - occupation
    EmployeeOccupation:
      type: string
      enum:
        - HousekeeperSupervisor
        - Housekeeper
        - Admin
        - Cook
    Housekeeper:
      type: object
      nullable: true
      properties:
        role:
          $ref: '#/components/schemas/HousekeeperRole'
        preferredFloor:
          type: integer
          nullable: true
      required:
        - role
    HousekeeperRole:
      type: string
      enum:
        - Kitchen
        - KitchenSupport
        - OnCall
    User:
      type: object
      description: User information for employee creation
      properties:
        userId:
          type: string
        photoUrl:
          type: string
          nullable: true
        isEnabled:
          type: boolean
        email:
          type: string
      required:
        - userId
        - isEnabled
        - email