ktor:
  application:
    modules:
      - com.portafolio.vientosdelsur.ApplicationKt.module
  deployment:
    port: 8080

database:
  jdbcUrl: $DATABASE_URL
  driverClassName: $DATABASE_DRIVER_CLASSNAME
  username: $DATABASE_USERNAME
  password: $DATABASE_PASSWORD
  maximumPoolSize: $MAX_POOL_SIZE