ktor:
  application:
    modules:
      - com.portafolio.vientosdelsur.ApplicationKt.module
  deployment:
    port: 8080

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/vientosdelsur"
  driverClassName: "org.postgresql.Driver"
  username: "postgres"
  password: "password"
  maximumPoolSize: 7