openapi: "3.1.0"
info:
  title: "VientosDelSur API"
  description: "VientosDelSur API"
  version: "1.0.0"
paths:
  /image-analysis:
    post:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
              examples:
                Example#1:
                  value: "Invalid multipart request"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseDto_AnalysisConclusion"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    BaseResponseDto:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - "message"
        - "timestamp"
    BaseResponseDto_AnalysisConclusion:
      type: "object"
      properties:
        message:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"